export interface ServiceInstance {
   key: string;
   name: string;
   path: string;
}
export interface Service {
   [key: string]: ServiceInstance;
}
export interface label {
   [key: string]: { text: string };
}
export interface numerics {
   [key: string]: { value: number };
}

export const Services: Service = {
   BASEURL: {
      key: "BASEURL",
      name: "BASEURL",
      path: "http://css-ihub-importer-svc.westeurope.cloudapp.azure.com:8080/",
   },
   UPLOAD: {
      key: "UPLOAD",
      name: "UPLOAD",
      path: "http://css-ihub-importer-svc.westeurope.cloudapp.azure.com:8080/import/upload",
   },
   ALLTXNS: {
      key: "ALLTXNS",
      name: "ALLTXNS",
      path: "http://css-ihub-transaction-manager-svc.westeurope.cloudapp.azure.com:8092/api/transactions/findAll",
   },
   PORTFOLIO: {
      key: "PORTFOLIO",
      name: "PORTFOLIO",
      path: "http://css-ihub-portfolio-manager-svc.westeurope.cloudapp.azure.com:8084/portfolio/findAllByAssetMgr/?customerId=1&assetMgr=NAM",
   },
   COUNTERPARTY: {
      key: "COUNTERPARTY",
      name: "COUNTERPARTY",
      path: "http://css-ihub-counterparty-manager-svc.westeurope.cloudapp.azure.com:8083/counterparty/findAllByCustomerId/?customerId=1",
   },
};

export const QAServices: Service = {
   UPLOAD: {
      key: "UPLOAD",
      name: "UPLOAD",
      path: "http://localhost:8080/import/upload",
   },
   ALLTXNS: {
      key: "ALLTXNS",
      name: "ALLTXNS",
      path: "http://localhost:8092/api/transactions/findAll",
   },
};

export const transactionDataFields2 = [
   { label: "Accrued Interest", value: "accrued interest" },
   { label: "Asset Mgr", value: "Asset Mgr" },
   { label: "Base Amount 2", value: "base amount 2" },
   { label: "Base Amount", value: "base amount" },
   { label: "Base Currency", value: "base currency" },
   { label: "Created Date", value: "CREATED DATE" },
   { label: "Contract Size", value: "Contract Size" },
   { label: "Counterparty", value: "Counterparty" },
   { label: "Currency", value: "CURRENCY" },
   { label: "External Trade ID", value: "External Trade ID" },
   { label: "Forward Rate", value: "forward rate" },
   { label: "FX Type", value: "FX Type" },
   { label: "Instrument", value: "Instrument" },
   { label: "Instrument Type", value: "instrument type" },
   { label: "Inverted", value: "inverted" },
   { label: "Maturity Date", value: "Maturity Date" },
   { label: "Nominal", value: "NOMINAL" },
   { label: "Payment Amount", value: "payment amount" },
   { label: "Portfolio", value: "Portfolio" },
   { label: "Price", value: "PRICE" },
   { label: "Quote Amount 2", value: "quote amount 2" },
   { label: "Quote Amount", value: "quote amount" },
   { label: "Quote Currency", value: "quote currency" },
   { label: "Settlement Date", value: "Settlement date" },
   { label: "Spot Rate", value: "spot rate" },
   { label: "Static Requested", value: "Static Requested" },
   { label: "Status", value: "Status" },
   { label: "Transaction Code", value: "Transaction Code" },
   { label: "Transaction Type", value: "TRANSACTION TYPE" },
   { label: "Trade Date", value: "Trade Date" },
   { label: "Trade ID", value: "Trade ID", disabled: true },
   { label: "Transaction Code", value: "Transaction Code" },
   { label: "Transaction Type", value: "TRANSACTION TYPE" },
   { label: "Transferred", value: "TRANSFERRED" },
   { label: "Yield", value: "yield" },
];

export const transactionLabels: label = {
   TRANSACTION_ID: { text: "Trade ID" },
   COUNTERPARTY_ID: { text: "Counterparty" },
   COUNTERPARTY_NAME: { text: "Counterparty" },
   TRADE_DATE: { text: "Trade Date" },
   TRANSACTION_CODE: { text: "Transaction Code" },
   INSTRUMENT: { text: "Instrument" },
   INSTRUMENT_SHORT: { text: "Instrument" },
   PORTFOLIO_SHORT: { text: "Portfolio Short" },
   ASSET_MANAGER: { text: "Asset Mgr" },
   PORTFOLIO_NAME: { text: "Portfolio" },
   STATUS: { text: "Status" },
   FX: { text: "FX" },
   NOMINAL: { text: "NOMINAL" },
   PRICE: { text: "PRICE" },
   PAYMENTAMOUNT: { text: "Payment Amount" },
   CURRENCY: { text: "CURRENCY" },
   EXTERNALTRADEID: { text: "External Trade ID" },
   TRANSFERRED: { text: "TRANSFERRED" },
   TRANSACTION_TYPE: { text: "TRANSACTION TYPE" },
   CREADTED_DATE: { text: "CREATED DATE" },
   SETTLEMENT_DATE: { text: "Settlement date" },
   INSTRUMENT_TYPE: { text: "instrument type" },
   PAYMENT_AMOUNT: { text: "payment amount" },
   ACCRUEDINTEREST: { text: "accrued interest" },
   YIELD: { text: "yield" },
   CONTRACTSIZE: { text: "Contract Size" },
   BROKER: { text: "broker" },
   MATURITYDATE: { text: "Maturity Date" },
   FX_TYPE: { text: "FX Type" },
   SPOT_RATE: { text: "spot rate" },
   FORWARD_RATE: { text: "forward rate" },
   BASE_CURRENCY: { text: "base currency" },
   QUOTE_CURRENCY: { text: "quote currency" },
   INVERTED: { text: "inverted" },
   BASE_AMOUNT: { text: "base amount" },
   QUOTE_AMOUNT: { text: "quote amount" },
   BASE_AMOUNT2: { text: "base amount 2" },
   QUOTE_AMOUNT2: { text: "quote amount 2" },
   STATIC_REQUESTED: { text: "Static Requested" },
   POSITIONID: { text: "Position ID" },
   NOTIONAL_AMOUNT: { text: "Notional Amount" },
   NO_OF_UNDERLYING_UNITS: { text: "No of Underlying Units" },
   VALUE_DATE: { text: "Value Date" },
   UNDERLYINGPRICE: { text: "Underlying Price" },
   INDEX: { text: "Index" },
   OTCINSTRUMENTID: { text: "Otc Instrument Id" },
   OTCINSTRUMENTTYPE: { text: "Otc Instrument Type" },
   EFFECTIVE_DATE: { text: "Effective Date" },
   OTC_TRANSACTION_CODE: { text: "OTC Transaction Code" },
   OTC_INSTRUMENT_TYPE: { text: "OTC Instrument Type" },
   OTC_INSTRUMENT_NAME: { text: "OTC Instrument Name" },
   QUANTITY: { text: "Quantity" },
   VERSION_DATE: { text: "Version Date" },
};

export const transactionDataFields: label = {
   CounterpartyId: { text: "CounterpartyId" },
   counterpartyName: { text: "counterpartyName" },
   counterpartyShort: { text: "counterpartyShort" },
   portfolioShort: { text: "portfolioShort" },
   portfolioName: { text: "portfolioName" },
   assetManager: { text: "assetMgr" },
   valueDate: { text: "tradeDate" },
   transactionCode: { text: "transactionCode" },
   instrumentShort: { text: "instrumentShort" },
   instrumentName: { text: "instrumentName" },
   transOriginNumber: { text: "transoriginNo" },
   action: { text: "action" },
   fxType: { text: "fxType" },
   nominal: { text: "nominal" },
   price: { text: "price" },
   paymentAmount: { text: "paymentAmount" },
   currency: { text: "currency" },
   externalTradeId: { text: "externalTradeId" },
   transferred: { text: "transferred" },
   transactionType: { text: "transactionType" },
   createdDate: { text: "createdDate" },
   status: { text: "action" },
   instrument_type: { text: "instrumentType" },
   payment_amount: { text: "paymentAmount" },
   settlement_date: { text: "settlementDate" },
   accruedinterest: { text: "accruedInterest" },
   yield: { text: "yield" },
   instrumentType: { text: "instrumentType" },
   contractSize: { text: "contractSize" },
   broker: { text: "broker" },
   maturity_date: { text: "maturityDate" },
   fx_type: { text: "fxType" },
   spot_rate: { text: "spotRate" },
   forward_rate: { text: "forwardRate" },
   base_currency: { text: "baseCurrency" },
   quote_currency: { text: "quoteCurrency" },
   Inverted: { text: "inverted" },
   base_amount: { text: "baseAmount" },
   quote_amount: { text: "quoteAmount" },
   base_amount2: { text: "baseAmount2" },
   quote_amount2: { text: "quoteAmount2" },
   staticRequested: { text: "staticRequested" },
   position_id: { text: "positionId" },
   notional_amount: { text: "notionalAmount" },
   noOfUnderlyingUnits: { text: "noOfUnderlyingUnits" },
   currencyLeg1: { text: "currencyLeg1" },
   newValueDate: { text: "valueDate" },
   underLyingPrice: { text: "underLyingPrice" },
   index: { text: "index" },
   otc_instrument_id: { text: "otcInstrumentId" },
   otc_instrument_type: { text: "otcInstrumentType" },
   effective_date: { text: "effectiveDate" },
   otc_transaction_code: { text: "otcTransactionCode" },
   tradeDate: { text: "tradeDate" },
   otcTransactionCode: { text: "otcTransactionCode" },
   otcInstrumentType: { text: "otcInstrumentType" },
   otcInstrumentName: { text: "otcInstrumentName" },
   quantity: { text: "quantity" },
   version_date: { text: "version_created" },
};

export const configurationTextFields = {
   NAME: { text: "Configuration Name" },
   TYPE: { text: "Type" },
   TXNTYPE: { text: "Transaction Type" },
   FILETYPE: { text: "File Type" },
   ASSETMGR: { text: "Asset Managers" },
   MODIFIED_AT: { text: "Modified Timestamp" },
   MODIFIED_BY: { text: "Modified By" },
};

export const configurationDataFields = {
   NAME: { text: "name" },
   TYPE: { text: "fileUpload" },
   TXNTYPE: { text: "transactionType" },
   FILETYPE: { text: "fileFormat" },
   ASSETMGR: { text: "assetManagers" },
   MODIFIED_AT: { text: "modified" },
   MODIFIED_BY: { text: "modifiedBy" },
};

export const exportConfigurationTextFields = {
   NAME: { text: "Configuration Name" },
   FILE_FORMAT: { text: "File Format" },
   SEND_MODE: { text: "Send Mode" },
   ASSETMGR: { text: "Asset Managers" },
   MODIFIED_AT: { text: "Modified Timestamp" },
   MODIFIED_BY: { text: "Modified By" },
   CREATED_AT: { text: "Created Timestamp" },
};

export const exportConfigurationDataFields = {
   NAME: { text: "name" },
   FILE_FORMAT: { text: "fileFormat" },
   SEND_MODE: { text: "sendMode" },
   ASSETMGR: { text: "assetManagers" },
   MODIFIED_AT: { text: "modified" },
   MODIFIED_BY: { text: "modifiedBy" },
   CREATED_AT: { text: "created" },
};
export const allTransactionPopUp = [
   { text: "Accrued Interest", fieldName: "accruedInterest" },
   { text: "Action", fieldName: "action" },
   { text: "Arrival Time", fieldName: "arrivalTime" },
   { text: "Arrival Price", fieldName: "arrivalPrice" },
   { text: "Asset Mgr", fieldName: "Asset_mgr" },
   { text: "Asset Mgr", fieldName: "assetMgr" },
   { text: "BIC Code", fieldName: "Biccode" },
   { text: "Base Amount 2", fieldName: "baseAmount2" },
   { text: "Base Amount", fieldName: "baseAmount" },
   { text: "Base Currency", fieldName: "baseCurrency" },
   { text: "Bloomberg ID", fieldName: "bloombergId" },
   { text: "Broker BIC Code", fieldName: "brokerBicCode" },
   { text: "Broker Name", fieldName: "brokerName" },
   { text: "Broker Short", fieldName: "brokerShort" },
   { text: "By", fieldName: "User" },
   { text: "CUSIP", fieldName: "cusip" },
   { text: "Cancelled By", fieldName: "authorDeleted" },
   { text: "Cancelled Date/Time", fieldName: "deletedDate" },
   { text: "Clean Value", fieldName: "cleanValue" },
   { text: "Comment", fieldName: "comment" },
   { text: "Comments", fieldName: "comments" },
   { text: "Confirmed By", fieldName: "authorConfirmed" },
   { text: "Confirmed Date/Time", fieldName: "confirmedDate" },
   { text: "Contract Size", fieldName: "contractSize" },
   { text: "Counterparty Bic Code", fieldName: "counterpartyBicCode" },
   { text: "Counterparty Name", fieldName: "counterpartyName" },
   { text: "Counterparty Short", fieldName: "counterpartyShort" },
   { text: "Counterparty LEI", fieldName: "counterpartyLei" },
   { text: "Coupon Rate", fieldName: "couponRate" },
   { text: "Created By", fieldName: "authorCreated" },
   { text: "Created Date/Time", fieldName: "createdDate" },
   { text: "Currency Pair", fieldName: "currencyPair" },
   { text: "Currency", fieldName: "currency" },
   { text: "Currency Leg 1", fieldName: "currencyLeg1" },
   { text: "Currency Leg 2", fieldName: "currencyLeg2" },
   { text: "Day Count Leg 1", fieldName: "daycountLeg1" },
   { text: "Day Count Leg 2", fieldName: "daycountLeg2" },
   { text: "Exchange", fieldName: "exchange" },
   { text: "Export Configuration ID", fieldName: "exportConfigurationId" },
   { text: "External Trade ID", fieldName: "externalTradeId" },
   { text: "FX Type", fieldName: "fxType" },
   { text: "Face Value", fieldName: "faceValue" },
   { text: "Factor", fieldName: "factor" },
   { text: "Fee1", fieldName: "fee1" },
   { text: "Fee2", fieldName: "fee2" },
   { text: "Fee3", fieldName: "fee3" },
   { text: "Fee4", fieldName: "fee4" },
   { text: "File Name", fieldName: "fileName" },
   { text: "First Valuation Date", fieldName: "firstValuationDate" },
   { text: "Forward Rate", fieldName: "forwardRate" },
   { text: "Frequency Leg 1", fieldName: "frequencyLeg1" },
   { text: "Frequency Leg 2", fieldName: "frequencyLeg2" },
   { text: "ISIN", fieldName: "isin" },
   { text: "Import Configuration ID", fieldName: "importConfigurationId" },
   { text: "Initial Valuation Date", fieldName: "initialValuationDate" },
   { text: "Instrument Name", fieldName: "instrumentName" },
   { text: "Instrument Short", fieldName: "instrumentShort" },
   { text: "Instrument Type", fieldName: "instrumentType" },
   { text: "Interest Rate", fieldName: "interestRate" },
   { text: "Margin Factor", fieldName: "marginFactor" },
   { text: "Maturity Date", fieldName: "maturityDate" },
   { text: "Modified By", fieldName: "authorModified" },
   { text: "Nominal", fieldName: "nominal" },
   { text: "PSET Full", fieldName: "psetFull" },
   { text: "Paid Received Leg 1", fieldName: "paidReceivedLeg1" },
   { text: "Paid Received Leg 2", fieldName: "paidReceivedLeg2" },
   { text: "Payment Amount", fieldName: "paymentAmount" },
   { text: "Pool Factor", fieldName: "poolFactor" },
   { text: "Portfolio Name", fieldName: "portfolioName" },
   { text: "Portfolio Short", fieldName: "portfolioShort" },
   { text: "Price", fieldName: "price" },
   { text: "Quantity", fieldName: "quantity" },
   { text: "Quote Amount 2", fieldName: "quoteAmount2" },
   { text: "Quote Amount", fieldName: "quoteAmount" },
   { text: "Quote Currency", fieldName: "quoteCurrency" },
   { text: "Quote Factor", fieldName: "quoteFactor" },
   { text: "Ref Rate", fieldName: "refRate" },
   { text: "Rate Type", fieldName: "rateType" },
   { text: "RIC", fieldName: "ric" },
   { text: "SEDOL", fieldName: "sedol" },
   { text: "Security ID", fieldName: "otcInstrumentId" },
   { text: "Security Name", fieldName: "otcInstrumentName" },
   { text: "Security Number", fieldName: "otcInstrumentNumber" },
   { text: "Security Type", fieldName: "otcInstrumentType" },
   { text: "Settlement Amount", fieldName: "settlementAmount" },
   { text: "Settlement Currency", fieldName: "settlementCurrency" },
   { text: "Settlement Date", fieldName: "settlementDate" },
   { text: "Spot Rate", fieldName: "spotRate" },
   { text: "Spread Rate", fieldName: "spreadRate" },
   { text: "Static Requested", fieldName: "staticRequested" },
   { text: "Sub Portfolio Name", fieldName: "sub_portfolio_name" },
   { text: "Sub Portfolio", fieldName: "subPortfolio" },
   { text: "Trade Date", fieldName: "tradeDate" },
   { text: "Trade", fieldName: "trader" },
   { text: "Transaction Code", fieldName: "transactionCode" },
   { text: "Transaction Type", fieldName: "transactionType" },
   { text: "Transferred Date", fieldName: "TransferredDate" },
   { text: "Transferred", fieldName: "transferred" },
   {
      text: "Underlying Security Currency",
      field: "underlyingSecurityCurrency",
   },
   { text: "Underlying Security Type", field: "underlyingSecurityType" },
   {
      text: "Underlying Security Indentifier",
      field: "underlyingSecurityIdentifier",
   },
   { text: "Updated By", fieldName: "authorUpdated" },
   { text: "Updated Date/Time", fieldName: "updatedDate" },
   { text: "UTI", fieldName: "uti" },
   { text: "Effective Date", fieldName: "valueDate" },
   { text: "Index", fieldName: "index" },
   { text: "Index Tenor", fieldName: "indexTenor" },
   { text: "Arrival Price", fieldName: "arrivalPrice" },
   { text: "Arrival price date Time", fieldName: "arrivalPriceDateTime" },
   { text: "Admin comments", fieldName: "adminComments" },
   { text: "Upfront Fee", fieldName: "upFrontFee" },
   { text: "Payment Date", fieldName: "paymentDate" },
   { text: "Spread", fieldName: "spread" },
   { text: "InitialRate", fieldName: "initialRate" },
   { text: "Maturity Date", fieldName: "maturityDate" },
   { text: "Notional", fieldName: "notionalAmount" },
];

export const TRSTransactionPopup = [
   { text: "Accured Interest", fieldName: "accuredInterest" },
   { text: "Action", fieldName: "action" },
   { text: "Asset Mgr", fieldName: "Asset_mgr" },
   { text: "Asset Mgr", fieldName: "assetMgr" },
   { text: "BIC Code", fieldName: "Biccode" },
   { text: "Bloomberg ID", fieldName: "bloombergId" },
   { text: "By", fieldName: "User" },
   { text: "CUSIP", fieldName: "cusip" },
   { text: "Cancelled By", fieldName: "authorDeleted" },
   { text: "Cancelled Date/Time", fieldName: "deletedDate" },
   { text: "Clean Value", fieldName: "cleanValue" },
   { text: "Comment", fieldName: "comment" },
   { text: "Comments", fieldName: "comments" },
   { text: "Confirmed By", fieldName: "authorConfirmed" },
   { text: "Confirmed Date/Time", fieldName: "confirmedDate" },
   { text: "Contract Size", fieldName: "contractSize" },
   { text: "Counterparty Bic Code", fieldName: "counterpartyBicCode" },
   { text: "Counterparty Name", fieldName: "counterpartyName" },
   { text: "Counterparty Short", fieldName: "counterpartyShort" },
   { text: "Counterparty LEI", fieldName: "counterpartyLei" },
   { text: "Coupon Rate", fieldName: "couponRate" },
   { text: "Created By", fieldName: "authorCreated" },
   { text: "Created Date/Time", fieldName: "createdDate" },
   { text: "Currency Pair", fieldName: "currencyPair" },

   { text: "Currency Leg 1", fieldName: "currencyLeg1" },
   { text: "Currency Leg 2", fieldName: "currencyLeg2" },
   { text: "Day Count Leg 1", fieldName: "daycountLeg1" },
   { text: "Day Count Leg 2", fieldName: "daycountLeg2" },
   { text: "Exchange", fieldName: "exchange" },
   { text: "Export Configuration ID", fieldName: "exportConfigurationId" },
   { text: "External Trade ID", fieldName: "externalTradeId" },
   { text: "File Name", fieldName: "fileName" },
   { text: "First Valuation Date", fieldName: "firstValuationDate" },
   { text: "Forward Rate", fieldName: "forwardRate" },
   { text: "Frequency Leg 1", fieldName: "frequencyLeg1" },
   { text: "Frequency Leg 2", fieldName: "frequencyLeg2" },
   { text: "ISIN", fieldName: "isin" },
   { text: "Import Configuration ID", fieldName: "importConfigurationId" },
   { text: "Initial Valuation Date", fieldName: "initialValuationDate" },
   { text: "Instrument Name", fieldName: "instrumentName" },
   { text: "Instrument Short", fieldName: "instrumentShort" },
   { text: "Margin Factor", fieldName: "marginFactor" },
   { text: "Maturity Date", fieldName: "maturityDate" },
   { text: "Modified By", fieldName: "authorModified" },
   { text: "Nominal", fieldName: "nominal" },
   { text: "OTC Instrument ID", fieldName: "otcInstrumentId" },
   { text: "OTC Instrument Name", fieldName: "otcInstrumentName" },
   { text: "OTC Instrument Number", fieldName: "otcInstrumentNumber" },
   { text: "OTC Instrument Type", fieldName: "otcInstrumentType" },
   { text: "OTC Transaction Code", fieldName: "otcTransactionCode" },
   { text: "PSET Full", fieldName: "psetFull" },
   { text: "Paid Received Leg 1", fieldName: "paidReceivedLeg1" },
   { text: "Paid Received Leg 2", fieldName: "paidReceivedLeg2" },
   { text: "Payment Amount", fieldName: "paymentAmount" },
   { text: "Pool Factor", fieldName: "poolFactor" },
   { text: "Portfolio Name", fieldName: "portfolioName" },
   { text: "Portfolio Short", fieldName: "portfolioShort" },

   { text: "Quantity", fieldName: "quantity" },
   { text: "Ref Rate", fieldName: "refRate" },
   { text: "Rate Type", fieldName: "rateType" },
   { text: "RIC", fieldName: "ric" },
   { text: "SEDOL", fieldName: "sedol" },
   { text: "Spot Rate", fieldName: "spotRate" },
   { text: "Spread Rate", fieldName: "spreadRate" },
   { text: "Static Requested", fieldName: "staticRequested" },
   { text: "Sub Portfolio Name", fieldName: "sub_portfolio_name" },
   { text: "Sub Portfolio", fieldName: "subPortfolio" },
   { text: "Trade Date", fieldName: "tradeDate" },
   { text: "Trade", fieldName: "trader" },
   { text: "Transaction Code", fieldName: "transactionCode" },
   { text: "Transaction Type", fieldName: "transactionType" },
   { text: "Transferred Date", fieldName: "TransferredDate" },
   { text: "Transferred", fieldName: "transferred" },
   { text: "Price", fieldName: "price" },
   { text: "Instrument Type", fieldName: "instrumentType" },

   {
      text: "Underlying Security Currency",
      field: "underlyingSecurityCurrency",
   },
   { text: "Currency", fieldName: "currency" },

   { text: "Updated By", fieldName: "authorUpdated" },
   { text: "Updated Date/Time", fieldName: "updatedDate" },
   { text: "UTI", fieldName: "uti" },
   { text: "Value Date", fieldName: "Value date" },
   { text: "Yield", fieldName: "yield" },
];

export const reportFields: label = {
   reportName: { text: "Report" },
   creationDate: { text: "Creation Date" },
   assetMgr: { text: "Asset Manager" },
};

export const reportDataFields: label = {
   fileName: { text: "fileName" },
   recievedDate: { text: "received" },
   assetMgr: { text: "assetMgr" },
};

export const ihubConstants: numerics = {
   type_ahead_manual_transaction_characters: { value: 3 },
   enter_key_code: { value: 13 },
   up_arrow_code: { value: 38 },
   down_arrow_code: { value: 40 },
   loaderTimer: { value: 2000 },
};

export const transactionStatus = [
   { label: "Confirm", value: "CON" },
   { label: "Cancelled", value: "CAN" },
   { label: "New", value: "NEW" },
];

export const transactionTypeSearch = [
   { label: "Bond", value: "BOND" },
   { label: "Equity", value: "EQUITY" },
   { label: "Future", value: "FUTURE" },
   { label: "FX", value: "FX" },
   { label: "Option", value: "OPTION" },
];
export const configSDRTransactionTypes = [
   { label: "Bond", value: "BOND" },
   { label: "Equity", value: "EQUITY" },
   { label: "Future", value: "FUTURE" },
   { label: "FX", value: "FX" },
   { label: "Option", value: "OPTION" },
   { label: "Cfd", value: "CFD" },
   { label: "Cds", value: "CDS" },
   { label: "Irs", value: "IRS" },
   { label: "Trs", value: "TRS" },
   { label: "Deposit", value: "DEPOSIT" },
   { label: "Repo", value: "REPOS" },
];

export const transactionTypes = {
   EQUITY: "EQ",
   BOND: "BO",
   FX: "FX",
   CFD: "CF",
   OPTION: "OP",
   FUTURE: "FU",
   OPEN_INTEREST: "OI",
   CASH: "CA",
   DEPOSIT: "DE",
   FRA: "FR",
   FORWARD: "FO",
   IRS: "IRS",
   CASH_PAYMENT: "CP",
   CASH_TRANSFER: "CT",
   FUNDORDER: "FUO",
   FX_NDF: "NDF",
   FX_SWAP: "SW",
   REPOS: "RE",
   SECURITY_LENDING: "SL",
   TRS: "TRS",
   TRS_ADJUST: "TA",
   EQUITY_FULL: "EQUITY",
   BOND_FULL: "BOND",
   OPTION_FULL: "OPTION",
   FUTURE_FULL: "FUTURE",
   OTC: "OTC",
   CDS: "CD",
};

export const operationTypes = {
   CREATE: "NEW",
   READ: "READ",
   UPDATE: "UPDATE",
   DELETE: "DELETE",
};

export const bondTransactionNumericDataFields = {
   dealCouponRate: "dealCouponRate",
   dealNominal: "dealNominal",
   dealFaceValue: "dealFaceValue",
   dealPoolFactor: "dealPoolFactor",
   dealQuoteFactor: "dealQuoteFactor",
   dealPrice: "dealPrice",
   dealYield: "dealYield",
   dealAccruedInterest: "dealAccruedInterest",
   dealCleanValue: "dealCleanValue",
   dealCurrency: "dealCurrency",
   dealSettlementCurrency: "dealSettlementCurrency",
   dealTradeDate: "dealTradeDate",
   dealValueDate: "dealValueDate",
   dealMaturityDate: "dealMaturityDate",
   dealCommission: "dealCommission",
   dealOtherFee: "dealOtherFee",
   dealTax: "dealTax",
   dealPaymentAmount: "dealPaymentAmount",
   dealSettlementAmount: "dealSettlementAmount",
   dealTransactionCode: "dealTransactionCode",
};

export const bondTypes = {
   ABS: "ABS",
   MBS: "MBS",
   BOND: "Bond",
   INDEX_BOND: "Index bond",
};

export const FXTypes = ["FXSwap", "Forward", "Spot", "NDF"];

export const FXTypesValues = {
   FXSwap: "FXSwap",
   Forward: "Forward",
   Spot: "Spot",
   NDF: "NDF",
};

export const FXTransactionNumericFields = {
   dealTransactionCode: "dealTransactionCode",
   dealCurrency: "dealCurrency",
   dealSettlementCurrency: "dealSettlementCurrency",
   dealTradeDate: "dealTradeDate",
   dealValueDate: "dealValueDate",
   dealMaturityDate: "dealMaturityDate",
   dealQuantity: "dealQuantity",
   dealPriceAmount: "dealPriceAmount",
   dealSettlementAmount: "dealSettlementAmount",
   dealCLS: "dealCLS",
   dealCurrencyPair: "dealCurrencyPair",
   dealFXType: "dealFXType",
   dealSpotRate: "dealSpotRate",
   dealTics: "dealTics",
   dealForwardRate: "dealForwardRate",
   dealBaseAmount: "dealBaseAmount",
   dealBaseCurrency: "dealBaseCurrency",
   //for FXSwap
   dealBaseCurrencyAmountSpot: "dealBaseCurrencyAmountSpot",
   dealBaseCurrencyAmountForward: "dealBaseCurrencyAmountForward",
   dealPriceCurrencyAmountSpot: "dealPriceCurrencyAmountSpot",
   dealPriceCurrencyAmountForward: "dealPriceCurrencyAmountForward",
};

export const allowedEvents = [
   "click",
   "mousemove",
   "contentmenu",
   "keyup",
   "keydown",
   "keypress",
   "wheel",
];

export const serverErrorMessage = {
   error500: "there is a server Error",
   error502: "there is a gateway Error",
   error400: "there is an error in the  Request",
   error403: "your are not authrized ",
   error404: "no url found",
};
export const fileErrorMessage = {
   errorBOND: "Bond Page Error",
   errorBONDMANUAL: "Bond Maunal  Page Error",
   errorBONDSERVICE: "Bond service Page Error",
   errorEQUITY: "Equity Page Error",
   errorCFD: "CFD Page Error",
   errorFUTURE: "Future Page Error",
   errorFX: "Fx Page Error",
   errorOPTION: "Option Page Error",
   errorSTATICDATA: "Static Data Page Error",
   errorSERVICEWORK: "Service Work page Error",
   errorLOGIN: "Service Work page Error",
   errorISLOGIN: "is login page Error",
   errorCONFIGURATIONS: "CONFIGURATIONS page Error",
   errorCONFIGURATIONSERVICE: "CONFIGURATIONSERVICE page Error",
   errorMAPPINGCONFIGURATION: "MAPPINGCONFIGURATION page Error",
   errorTRANSACTIONSERVICE: "TRANSACTIONSERVICE page error",
   errorTRANSACTIONTABLE: "TRANSACTIONTABLE page error",
   errorUPLOADSERVICE: "Upload Service page error",
   errorPORTFOLIOSERVICE: "Portfolio Service page error",
   errorPORTFOLIOPAGE: "Portfolio tsx Page error",
   errorINSTRUMENTTABLE: "INSTRUMENTTABLE page error",
   errorINSTRUMENTSTRANS: "INSTRUMENTSTRANSACTION TYPE page error",
   errorINSTRUMENTSERVICE: "errorINSTRUMENTSERVICE page Error",
   errorCURRENCYCROSS: "CURRENCYCROSS  page Error",
   errorINSTRUMENTFUTURETABLE: "INSTRUMENTFUTURETABLE page Error",
   errorCURRENCYCROSSSERVICE: "CURRENCYCROSSSERVICE page Error",
   errorINSTRUMENTBONDTABLE: "INSTRUMENTBONDTABLE page Error",
   errorCOUNTERPARTYTABLE: "COUNTERPARTYTABLE page Error",
   errorCOUNTERPARTYSERVICE: "COUNTERPARTYSERVICE page Error",
   errorREPORTTABLE: "REPORTTABLE page Error",
   errorREPORTSERVICE: "REPORTSERVICE page Error",
   errorOPTIONSERVICE: "OPTIONSERVICE page Error",
   errorOPTIONMANUALTRANS: "OPTIONMANUALTRANS page Error",
   errorFXMANUALTRANS: "FXMANUALTRANS page Error",
   errorFUTURESERVICE: "FUTURESERVICE page Error",
   errorFUTUREMANUALTRANS: "FUTUREMANUALTRANS page Error",
   errorEQUITYSERVICE: "EQUITYSERVICE page Error",
   errorEQUITYMANUALTRANS: "EQUITYMANUALTRANS page Error",
   errorDEALSERVICE: "DEALSERVICE page Error",
   errorCOMMONSERVICE: "COMMONSERVICE page Error",
   errorCFDMANUALTRANS: "CFDMANUALTRANS page Error",
   errorCFDSERVICE: "CFDSERVICE page Error",
   errorREPORTPAGE: "REPORT PAGE Error ",
};

export const logDataFields: label = {
   LOG_ID: { text: "id" },
   CUSTOMER_ID: { text: "customerId" },
   ASSETMGR: { text: "assetMgr" },
   JOB: { text: "job" },
   CREATED: { text: "created" },
   SUCCESS: { text: "success" },
   FILENAME: { text: "fileName" },
   COMMENT: { text: "comment" },
};

export const logLabels: label = {
   LOG_ID: { text: "Log ID" },
   CUSTOMER_ID: { text: "customer ID" },
   ASSETMGR: { text: "Asset Mgr" },
   JOB: { text: "Service" },
   CREATED: { text: "Created Date" },
   SUCCESS: { text: "Success" },
   FILENAME: { text: "File Name" },
   COMMENT: { text: "Comment" },
};

export const userGroupDataFields: label = {
   SHORT_NAME: { text: "shortname" },
   LONG_NAME: { text: "name" },
   EMAIL_NOTIFICATION: { text: "errorEmail" },
};

export const userGroupLabels: label = {
   SHORT_NAME: { text: "Short Name" },
   LONG_NAME: { text: "Long Name" },
   EMAIL_NOTIFICATION: { text: "Email Notification" },
   CREATED_TIME: { text: "Created Date" },
   LAST_LOGIN_TIME: { text: "Last Login Date" },
};

export const usersDataFields: label = {
   FIRST_NAME: { text: "firstname" },
   LAST_NAME: { text: "lastname" },
   ROLE: { text: "role" },
   ASSET_MANAGER: { text: "assetmgr" },
   EMAIL: { text: "email" },
   CREATED_TIME: { text: "created" },
   LAST_LOGIN_TIME: { text: "last_login" },
   LAST_LOGIN: { text: "lastLogin" },
};

export const usersLabels: label = {
   FIRST_NAME: { text: "First Name" },
   LAST_NAME: { text: "Last Name" },
   ROLE: { text: "Role" },
   ASSET_MANAGER: { text: "Asset Manager" },
   EMAIL: { text: "Email" },
   CREATED_TIME: { text: "Created Date" },
   LAST_LOGIN_TIME: { text: "Last Login Date" },
};

export const timeZones = [
   { text: "UTC +9:30", value: "Australia/Darwin" },
   { text: "UTC +5:30", value: "Asia/Kolkata" },
   { text: "UTC +3", value: "Africa/Nairobi" },
   { text: "UTC +2", value: "Africa/Juba" },
   { text: "UTC +1", value: "Europe/Stockholm" },
   { text: "UTC ±0", value: "Europe/London" },
   { text: "UTC -4", value: "America/Barbados" },
   { text: "UTC -6", value: "America/Mexico_City" },
   { text: "UTC -5", value: "America/Toronto" },
   { text: "UTC -7", value: "America/Phoenix" },
   { text: "UTC -8", value: "America/Los_Angeles" },
];

export const arrivalTimeZones = [
   { text: "UTC +9:30", value: ":00.000+09:30" },
   { text: "UTC +5:30", value: ":00.000+05:30" },
   { text: "UTC +3", value: ":00.000+03:00" },
   { text: "UTC +2", value: ":00.000+02:00" },
   { text: "UTC +1", value: ":00.000+01:00" },
   { text: "UTC ±0", value: ":00.000+00:00" },
   { text: "UTC -4", value: ":00.000-04:00" },
   { text: "UTC -5", value: ":00.000-05:00" },
   { text: "UTC -6", value: ":00.000-06:00" },
   { text: "UTC -7", value: ":00.000-07:00" },
   { text: "UTC -8", value: ":00.000-08:00" },
];
export const staticRequestDataFields = {
   STATUS: { text: "status" },
   REQUEST_TYPE: { text: "requestType" },
   SECURITY_KEY: { text: "securityKey" },
   SECURITY_ID: { text: "securityId" },
   CURRENCY: { text: "currency" },
   EXCHANGE: { text: "exchange" },
   TRADE_REFERENCE: { text: "tradeReference" },
   ASSETMGR: { text: "assetMgr" },
   REQUEST_DATE: { text: "created" },
};
export const staticRequestTextFields = {
   STATUS: { text: "status" },
   REQUEST_TYPE: { text: "request type" },
   SECURITY_KEY: { text: "security key" },
   SECURITY_ID: { text: "security id" },
   CURRENCY: { text: "currency" },
   EXCHANGE: { text: "exchange" },
   TRADE_REFERENCE: { text: "trade reference" },
   ASSETMGR: { text: "asset manager" },
   REQUEST_DATE: { text: "requested date" },
};
